apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: turbinia-neg-healthcheck
spec:
  timeoutSec: 300
  healthCheck:
    checkIntervalSec: 5
    timeoutSec: 5
    healthyThreshold: 2
    unhealthyThreshold: 2
    type: HTTP
    requestPath: /ping
    port: 8080