{{- if and (.Values.ingress.enabled) (eq .Values.ingress.className "gce") }}
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ include "turbinia.fullname" . }}-backend-config
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "turbinia.labels" . | nindent 4 }}
spec:
  timeoutSec: 300
  healthCheck:
    checkIntervalSec: 5
    timeoutSec: 5
    healthyThreshold: 2
    unhealthyThreshold: 2
    type: HTTP
    requestPath: /ping
    port: 8080
{{- end }}