{{- if and (.Values.ingress.enabled) (eq .Values.ingress.className "gce") }}
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: {{ include "turbinia.fullname" . }}-managed-ssl
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "turbinia.labels" . | nindent 4 }}
spec:
  domains: 
    - {{ required "A valid .Values.ingress.host entry is required!" .Values.ingress.host }}
{{- end }}