apiVersion: v1
kind: Service
metadata:
  name: turbinia-api-service
  labels:
    app: turbinia-api-service
spec:
  ports:
  - name: svc
    port: 8000
    targetPort: 8000
  - name: metrics
    port: 9200
    targetPort: 9200
  selector:
    app: turbinia-api-server