apiVersion: v1
kind: Service
metadata:
  name: turbinia-worker-metrics
  labels:
    app: turbinia-worker-metrics
spec:
  ports:
  - port: 9200
    targetPort: 9200
  selector:
    app: turbinia-worker