apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: turbinia-neg-healthcheck
spec:
  timeoutSec: 300
  healthCheck:
    checkIntervalSec: 5
    timeoutSec: 5
    healthyThreshold: 2
    unhealthyThreshold: 2
    type: HTTP
    requestPath: /ping
    port: 8080
---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: turbinia-loadbalancer-frontend-config
spec:
  redirectToHttps:
    enabled: true
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: turbinia-loadbalancer-managed-ssl
spec:
  domains: 
    - <DOMAIN_NAME> 
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: turbinia-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "turbinia-webapps"
    networking.gke.io/managed-certificates: turbinia-loadbalancer-managed-ssl
    networking.gke.io/v1beta1.FrontendConfig: turbinia-loadbalancer-frontend-config
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
    - host: <DOMAIN_NAME>
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: turbinia-oauth2-service
                port:
                  number: 8080
  defaultBackend:
    service:
      name: turbinia-oauth2-service # Name of the Service targeted by the Ingress
      port:
        number: 8080 # Should match the port used by the Service