apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: turbinia-healthcheck-ng
spec:
  healthCheck:
    checkIntervalSec: 5
    timeoutSec: 5
    healthyThreshold: 2
    unhealthyThreshold: 2
    type: HTTP
    requestPath: /ping
    port: 9376