apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: turbinia
build:
  artifacts:
    # - image: turbinia-api-server
    #   docker:
    #     dockerfile: docker/api_server/Dockerfile
    # - image: turbinia-server
    #   docker:
    #     dockerfile: docker/server/Dockerfile
    - image: turbinia-worker
      docker:
        dockerfile: docker/worker/Dockerfile.dev
  #local:
    # useDockerCLI: true
    # useBuildkit: true 
    #concurrency: 0
    # tryImportMissing: true
deploy:
  helm:
    releases:
    - name: dev-release
      #remoteChart: oci://us-docker.pkg.dev/osdfir-registry/osdfir-charts/turbinia
      chartPath: ./charts/turbinia
      setValueTemplates:
        worker.image.repository: "{{.IMAGE_REPO_turbinia_worker}}"
        worker.image.tag: "{{.IMAGE_TAG_turbinia_worker}}@{{.IMAGE_DIGEST_turbinia_worker}}"
