# coding: utf-8

"""
    Turbinia API Server

    Turbinia API server  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import turbinia_api_lib
from turbinia_api_lib.models.complete_turbinia_stats import CompleteTurbiniaStats  # noqa: E501
from turbinia_api_lib.rest import ApiException

class TestCompleteTurbiniaStats(unittest.TestCase):
    """CompleteTurbiniaStats unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test CompleteTurbiniaStats
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CompleteTurbiniaStats`
        """
        model = turbinia_api_lib.models.complete_turbinia_stats.CompleteTurbiniaStats()  # noqa: E501
        if include_optional :
            return CompleteTurbiniaStats(
                all_tasks = None, 
                failed_tasks = None, 
                requests = None, 
                successful_tasks = None, 
                tasks_per_type = None, 
                tasks_per_user = None, 
                tasks_per_worker = None
            )
        else :
            return CompleteTurbiniaStats(
                all_tasks = None,
                failed_tasks = None,
                requests = None,
                successful_tasks = None,
                tasks_per_type = None,
                tasks_per_user = None,
                tasks_per_worker = None,
        )
        """

    def testCompleteTurbiniaStats(self):
        """Test CompleteTurbiniaStats"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
