"""
    Turbinia API Server

    Turbinia API server  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import turbinia_api_client
from turbinia_api_client.model.request_status import RequestStatus


class TestRequestStatus(unittest.TestCase):
    """RequestStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRequestStatus(self):
        """Test RequestStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RequestStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
