"""
    Turbinia API Server

    Turbinia API server  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import turbinia_api_client
from turbinia_api_client.model.request_status import RequestStatus
globals()['RequestStatus'] = RequestStatus
from turbinia_api_client.model.requests_summary import RequestsSummary


class TestRequestsSummary(unittest.TestCase):
    """RequestsSummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRequestsSummary(self):
        """Test RequestsSummary"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RequestsSummary()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
