# coding: utf-8

"""
    Turbinia API Server

    Turbinia is an open-source framework for deploying, managing, and running distributed forensic workloads

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from turbinia_api_lib.api.turbinia_jobs_api import TurbiniaJobsApi


class TestTurbiniaJobsApi(unittest.TestCase):
    """TurbiniaJobsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TurbiniaJobsApi()

    def tearDown(self) -> None:
        pass

    def test_read_jobs(self) -> None:
        """Test case for read_jobs

        Read Jobs
        """
        pass


if __name__ == '__main__':
    unittest.main()
