# coding: utf-8

"""
    Turbinia API Server

    Turbinia API server  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import turbinia_api_lib
from turbinia_api_lib.api.turbinia_evidence_api import TurbiniaEvidenceApi  # noqa: E501
from turbinia_api_lib.rest import ApiException


class TestTurbiniaEvidenceApi(unittest.TestCase):
    """TurbiniaEvidenceApi unit test stubs"""

    def setUp(self):
        self.api = turbinia_api_lib.api.turbinia_evidence_api.TurbiniaEvidenceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_evidence_attributes(self):
        """Test case for get_evidence_attributes

        Get Evidence Attributes  # noqa: E501
        """
        pass

    def test_get_evidence_by_id(self):
        """Test case for get_evidence_by_id

        Get Evidence By Id  # noqa: E501
        """
        pass

    def test_get_evidence_summary(self):
        """Test case for get_evidence_summary

        Get Evidence Summary  # noqa: E501
        """
        pass

    def test_get_evidence_types(self):
        """Test case for get_evidence_types

        Get Evidence Types  # noqa: E501
        """
        pass

    def test_query_evidence(self):
        """Test case for query_evidence

        Query Evidence  # noqa: E501
        """
        pass

    def test_upload_evidence(self):
        """Test case for upload_evidence

        Upload Evidence  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
