"""
    Turbinia API Server

    This is Turbinia's API server description.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import turbinia_api_client
from turbinia_api_client.model.base_evidence_options import BaseEvidenceOptions


class TestBaseEvidenceOptions(unittest.TestCase):
    """BaseEvidenceOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBaseEvidenceOptions(self):
        """Test BaseEvidenceOptions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BaseEvidenceOptions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
