"""
    Turbinia API Server

    This is Turbinia's API server description.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import turbinia_api_client
from turbinia_api_client.api.turbinia_configuration_api import TurbiniaConfigurationApi  # noqa: E501


class TestTurbiniaConfigurationApi(unittest.TestCase):
    """TurbiniaConfigurationApi unit test stubs"""

    def setUp(self):
        self.api = TurbiniaConfigurationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_read_config(self):
        """Test case for read_config

        Read Config  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
