"""
    Turbinia API Server

    Turbinia API server  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import turbinia_api_lib
from turbinia_api_lib.api.turbinia_jobs_api import TurbiniaJobsApi  # noqa: E501


class TestTurbiniaJobsApi(unittest.TestCase):
    """TurbiniaJobsApi unit test stubs"""

    def setUp(self):
        self.api = TurbiniaJobsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_read_jobs(self):
        """Test case for read_jobs

        Read Jobs  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
