# coding: utf-8

"""
    Turbinia API Server

    Turbinia is an open-source framework for deploying, managing, and running distributed forensic workloads

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from turbinia_api_lib.api.turbinia_requests_api import TurbiniaRequestsApi


class TestTurbiniaRequestsApi(unittest.TestCase):
    """TurbiniaRequestsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TurbiniaRequestsApi()

    def tearDown(self) -> None:
        pass

    def test_create_request(self) -> None:
        """Test case for create_request

        Create Request
        """
        pass

    def test_get_request_status(self) -> None:
        """Test case for get_request_status

        Get Request Status
        """
        pass

    def test_get_requests_summary(self) -> None:
        """Test case for get_requests_summary

        Get Requests Summary
        """
        pass


if __name__ == '__main__':
    unittest.main()
