# coding: utf-8

"""
    Turbinia API Server

    Turbinia is an open-source framework for deploying, managing, and running distributed forensic workloads

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from turbinia_api_lib.api.turbinia_evidence_api import TurbiniaEvidenceApi


class TestTurbiniaEvidenceApi(unittest.TestCase):
    """TurbiniaEvidenceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TurbiniaEvidenceApi()

    def tearDown(self) -> None:
        pass

    def test_get_evidence_attributes(self) -> None:
        """Test case for get_evidence_attributes

        Get Evidence Attributes
        """
        pass

    def test_get_evidence_by_id(self) -> None:
        """Test case for get_evidence_by_id

        Get Evidence By Id
        """
        pass

    def test_get_evidence_summary(self) -> None:
        """Test case for get_evidence_summary

        Get Evidence Summary
        """
        pass

    def test_get_evidence_types(self) -> None:
        """Test case for get_evidence_types

        Get Evidence Types
        """
        pass

    def test_query_evidence(self) -> None:
        """Test case for query_evidence

        Query Evidence
        """
        pass

    def test_upload_evidence(self) -> None:
        """Test case for upload_evidence

        Upload Evidence
        """
        pass


if __name__ == '__main__':
    unittest.main()
