# coding: utf-8

"""
    Turbinia API Server

    Turbinia is an open-source framework for deploying, managing, and running distributed forensic workloads

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from turbinia_api_lib.api.turbinia_configuration_api import TurbiniaConfigurationApi


class TestTurbiniaConfigurationApi(unittest.TestCase):
    """TurbiniaConfigurationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TurbiniaConfigurationApi()

    def tearDown(self) -> None:
        pass

    def test_get_request_options(self) -> None:
        """Test case for get_request_options

        Get Request Options
        """
        pass

    def test_read_config(self) -> None:
        """Test case for read_config

        Read Config
        """
        pass


if __name__ == '__main__':
    unittest.main()
