"""
    Turbinia API Server

    This is Turbinia's API server description.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import turbinia_api_client
from turbinia_api_client.api.logs_api import LogsApi  # noqa: E501


class TestLogsApi(unittest.TestCase):
    """LogsApi unit test stubs"""

    def setUp(self):
        self.api = LogsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_logs(self):
        """Test case for get_logs

        Get Logs  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
