# coding: utf-8

"""
    Turbinia API Server

    Turbinia is an open-source framework for deploying,managing, and running distributed forensic workloads  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import turbinia_api_lib
from turbinia_api_lib.model.complete_turbinia_stats import CompleteTurbiniaStats
from turbinia_api_lib import configuration


class TestCompleteTurbiniaStats(unittest.TestCase):
    """CompleteTurbiniaStats unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
