Log2timelineTask:
  required_flags: []
  required_params: ['partitions', 'volumes', 'vss_stores']
  allowed_flags: ['h', 'd', 'data', 'f', 'info', 'no_dependencies_check', 
                  'no_vss', 'q', 't', 'troubles', 'use_markdown', 'V', 
                  'vss_only', 'z']
  allowed_params: ['artifact_definitions', 'artifact_filters', 
      'artifact_filters_file', 'buffer_size', 'credential', 
      'custom_artifact_definitions', 'hasher_file_size_limit', 
      'hashers', 'logfile', 'parsers', 'partitions', 'preferred_year', 
      'process_archives', 'process_memory_limit', 'profilers', 
      'profiling_directory', 'profiling_sample_rate', 'queue_size', 
      'sigsegv_handler', 'single_process', 'skip_compressed_streams', 
      'status_view', 'storage_format', 'task_storage_format', 
      'temporary_directory', 'volumes', 'vss_stores', 'worker_memory_limit', 'workers', 'yara_rules']

ArtifactExtractionTask:
  required_flags: []
  required_params: ['partitions', 'volumes', 'vss_stores']
  allowed_flags: ['d', 'h', 'include_duplicates', 'no_vss', 
                  'q', 'troubles', 'V', 'vss_only'] 
  allowed_params: ['artifact_definitions', 'artifact_filters', 
      'artifact_filters_file', 'custom_artifact_definitions', 
      'data', 'date-filter', 'f', 'logfile', 'names', 'partitions',
      'process_memory_limit', 'signatures', 'volumes', 'vss_stores', 'w', 'x']


