{{- if and (.Values.metrics.enabled) (.Values.controller.enabled) -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "turbinia.fullname" . }}-controller-metrics
  labels:
    {{- include "turbinia.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.metrics.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: controller
    {{- include "turbinia.selectorLabels" . | nindent 4 }}
{{- end }}