{
 "title": "Turbinia Application Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total  Server Requests",
   "type": "stat",
   "description": "Total number of requests received by Turbinia Server",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(turbinia_server_request_total)"
    }
   ]
  },
  {
   "title": "Total Jobs",
   "type": "stat",
   "description": "Total number of Turbinia Jobs",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(turbinia_jobs_total)" }
   ]
  },
  {
   "title": "Completed Jobs",
   "type": "stat",
   "description": "Total number of completed Turbinia Jobs",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(turbinia_jobs_completed_total)"
    }
   ]
  },
  {
   "title": "Total Tasks ",
   "type": "stat",
   "description": "Total number of Tasks created by the Turbinia Server",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(turbinia_server_tasks_total)"
    }
   ]
  },
  {
   "title": "Completed Tasks",
   "type": "stat",
   "description": "Total number of Tasks completed",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(turbinia_server_tasks_completed_total)"
    }
   ]
  },
  {
   "title": "Tasks Failed",
   "type": "stat",
   "description": "Total number of Tasks failed",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(turbinia_worker_tasks_failed_total)"
    }
   ]
  },
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Jobs",
   "type": "graph",
   "description": "Displays Turbinia Job related information over a period of time",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(turbinia_jobs_total)", "legendFormat": "Total Jobs" },
    {
     "expr": "sum(turbinia_jobs_completed_total)",
     "legendFormat": "Completed Jobs"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "description": "Displays the number of Requests sent to the Turbinia Server over a period of time",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(turbinia_server_request_total)",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Server Tasks",
   "type": "graph",
   "description": "Displays Turbinia Server Task information over a period of time",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(turbinia_server_tasks_total)",
     "legendFormat": "Total Tasks"
    },
    {
     "expr": "sum(turbinia_server_tasks_completed_total)",
     "legendFormat": "Completed Tasks"
    }
   ]
  },
  {
   "title": "Worker Tasks",
   "type": "graph",
   "description": "Displays Turbinia Worker Task statistics over a period of time",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(turbinia_worker_tasks_completed_total)",
     "legendFormat": "Completed Tasks"
    },
    {
     "expr": "sum(turbinia_worker_tasks_failed_total)",
     "legendFormat": "Failed Tasks"
    },
    {
     "expr": "sum(turbinia_worker_tasks_queued_total)",
     "legendFormat": "Queued Tasks"
    },
    {
     "expr": "sum(turbinia_worker_tasks_started_total)",
     "legendFormat": "Started Tasks"
    }
   ]
  },
  {
   "title": "Failed Worker Tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum(turbinia_worker_tasks_failed_total)",
     "legendFormat": "Failed worker tasks"
    }
   ]
  }
 ]
}