{
 "title": "Turbinia Application Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Jobs",
   "type": "stat",
   "description": "This shows the total number of Turbinia Jobs.",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(turbinia_jobs_total)" }
   ]
  },
  {
   "title": "Total Jobs Completed",
   "type": "stat",
   "description": "This shows the total number of Turbinia Jobs completed.",
   "gridPos": { "h": 8, "w": 2, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(turbinia_jobs_completed_total)"
    }
   ]
  },
  {
   "title": "Total  Server Requests",
   "type": "stat",
   "description": "This indicates the total number of requests sent to the Turbinia Server",
   "gridPos": { "h": 8, "w": 2, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(turbinia_server_request_total)"
    }
   ]
  },
  {
   "title": "Total Server Tasks ",
   "type": "stat",
   "description": "This indicates the total number of Tasks the Turbinia Server has received.",
   "gridPos": { "h": 8, "w": 2, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(turbinia_server_tasks_total)"
    }
   ]
  },
  {
   "title": "Total Server Tasks Completed",
   "type": "stat",
   "description": "This displays the total number of Tasks completed as indicated by the Turbinia Server.",
   "gridPos": { "h": 8, "w": 2, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(turbinia_server_tasks_completed_total)"
    }
   ]
  },
  {
   "title": "Total Tasks Failed",
   "type": "stat",
   "description": "This displays the total Tasks failed as indicated by the Turbinia Worker.",
   "gridPos": { "h": 8, "w": 2, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(turbinia_worker_tasks_failed_total)"
    }
   ]
  },
  {
   "title": "Turbinia Server Stats",
   "type": "graph",
   "description": "Displays various metrics related to Turbinia Server requests and tasks.",
   "gridPos": { "h": 15, "w": 10, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "turbinia_server_request_total" },
    { "expr": "turbinia_server_tasks_total" },
    {
     "expr": "turbinia_server_tasks_completed_total"
    }
   ]
  },
  {
   "title": "Turbinia Worker Stats",
   "type": "graph",
   "description": "Displays various stats for the Turbinia Worker.",
   "gridPos": { "h": 15, "w": 12, "x": 10, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "turbinia_worker_tasks_completed_total"
    },
    {
     "expr": "turbinia_worker_tasks_queued_total"
    },
    {
     "expr": "turbinia_worker_tasks_failed_total"
    },
    {
     "expr": "turbinia_worker_tasks_started_total"
    }
   ]
  }
 ]
}