{
 "title": "Turbinia Health Check",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Turbinia Task Timeout",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(turbinia_worker_tasks_timeout_total)",
     "legendFormat": "Total timed out tasks"
    }
   ]
  },
  {
   "title": "Partition Enumeration Average Runtime",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "\navg(rate(partitionenumerationtask_duration_seconds_sum[30d])/rate(partitionenumerationtask_duration_seconds_count[30d]))",
     "legendFormat": "Partition Enumeration last 30 days average runtime"
    },
    {
     "expr": "\navg(rate(partitionenumerationtask_duration_seconds_sum[3d])/rate(partitionenumerationtask_duration_seconds_count[3d]))",
     "legendFormat": "Partition Enumeration last 3 days average runtime"
    }
   ]
  },
  {
   "title": "Psort Average Runtime",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "\navg(rate(psorttask_duration_seconds_sum[30d])/rate(psorttask_duration_seconds_count[30d]))",
     "legendFormat": "Psort last 30 days average runtime"
    },
    {
     "expr": "\navg(rate(psorttask_duration_seconds_sum[3d])/rate(psorttask_duration_seconds_count[3d]))",
     "legendFormat": "Psort last 3 days average runtime"
    }
   ]
  },
  {
   "title": "Plaso Average Runtime",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(plasotask_duration_seconds_sum[30d])/rate(plasotask_duration_seconds_count[30d]))",
     "legendFormat": "Plaso last 30 days average runtime"
    },
    {
     "expr": "avg(rate(plasotask_duration_seconds_sum[3d])/rate(plasotask_duration_seconds_count[3d]))",
     "legendFormat": "Plaso last 3 days average runtime"
    }
   ]
  },
  {
   "title": "Finalize Task Average Runtime",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "\navg(rate(finalizerequesttask_duration_seconds_sum[30d])/rate(finalizerequesttask_duration_seconds_count[30d]))",
     "legendFormat": "Finalize request last 30 days average runtime"
    },
    {
     "expr": "avg(rate(finalizerequesttask_duration_seconds_sum[3d])/rate(finalizerequesttask_duration_seconds_count[3d]))",
     "legendFormat": "Finalize request last 3 days average runtime"
    }
   ]
  },
  {
   "title": "Bulk Extractor Average Runtime",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "\navg(rate(bulkextractortask_duration_seconds_sum[30d])/rate(bulkextractortask_duration_seconds_count[30d]))",
     "legendFormat": "Bulk extractor last 30 days average runtime"
    },
    {
     "expr": "\navg(rate(bulkextractortask_duration_seconds_sum[3d])/rate(bulkextractortask_duration_seconds_count[3d]))",
     "legendFormat": "Bulk extractor last 3 days average runtime"
    },
    {
     "expr": "job:bulkextractortask_duration:rate3d:z_score",
     "legendFormat": "z_score"
    }
   ]
  },
  {
   "title": "Grep Task Average Runtime",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "\navg(rate(greptask_duration_seconds_sum[30d])/rate(greptask_duration_seconds_count[30d]))",
     "legendFormat": "Grep last 30 days average runtime"
    },
    {
     "expr": "\navg(rate(greptask_duration_seconds_sum[3d])/rate(greptask_duration_seconds_count[3d]))",
     "legendFormat": "Grep last 3 days average runtime"
    }
   ]
  },
  {
   "title": "Redis Average Runtime",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "\n\navg(rate(redisanalysistask_duration_seconds_sum[30d])/rate(redisanalysistask_duration_seconds_count[30d]))",
     "legendFormat": "Redis last 30 days average runtime"
    },
    {
     "expr": "\navg(rate(redisanalysistask_duration_seconds_sum[3d])/rate(redisanalysistask_duration_seconds_count[3d]))",
     "legendFormat": "Redis last 3 days average runtime"
    }
   ]
  },
  {
   "title": "Tomcat Average Runtime",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "\navg(rate(tomcatanalysistask_duration_seconds_sum[30d])/rate(tomcatanalysistask_duration_seconds_count[30d]))",
     "legendFormat": "Tomcat last 30 days average runtime"
    },
    {
     "expr": "avg(rate(tomcatanalysistask_duration_seconds_sum[3d])/rate(tomcatanalysistask_duration_seconds_count[3d]))",
     "legendFormat": "Tomcat last 3 days average runtime"
    }
   ]
  },
  {
   "title": "String ASCII Average Runtime",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "\navg(rate(stringsasciitask_duration_seconds_sum[30d])/rate(stringsasciitask_duration_seconds_count[30d]))",
     "legendFormat": "String last 30 days average runtime"
    },
    {
     "expr": "\navg(rate(stringsasciitask_duration_seconds_sum[3d])/rate(stringsasciitask_duration_seconds_count[3d]))",
     "legendFormat": "String last 3 days average runtime"
    }
   ]
  },
  {
   "title": "Jupyter  Average Runtime",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "\n\navg(rate(jupyteranalysistask_duration_seconds_sum[30d])/rate(jupyteranalysistask_duration_seconds_count[30d]))",
     "legendFormat": "Jupyter last 30 days average runtime"
    },
    {
     "expr": "\n\navg(rate(jupyteranalysistask_duration_seconds_sum[3d])/rate(jupyteranalysistask_duration_seconds_count[3d]))",
     "legendFormat": "Jupyter last 3 days average runtime"
    }
   ]
  },
  {
   "title": "Volatility Average Runtime",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "\navg(rate(volatilitytask_duration_seconds_sum[30d])/rate(volatilitytask_duration_seconds_count[30d]))",
     "legendFormat": "Volatility last 30 days average runtime"
    },
    {
     "expr": "\navg(rate(volatilitytask_duration_seconds_sum[3d])/rate(volatilitytask_duration_seconds_count[3d]))",
     "legendFormat": "Volatility last 3 days average runtime"
    }
   ]
  },
  {
   "title": "Stattask Average Runtime",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "\navg(rate(stattask_duration_seconds_sum[30d])/rate(stattask_duration_seconds_count[30d]))",
     "legendFormat": "Stat task last 30 days average runtime"
    },
    {
     "expr": "\navg(rate(stattask_duration_seconds_sum[3d])/rate(stattask_duration_seconds_count[3d]))",
     "legendFormat": "Stat task last 3 days average runtime"
    }
   ]
  },
  {
   "title": "Hindsight Average Runtime",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "\n\navg(rate(hindsighttask_duration_seconds_sum[30d])/rate(hindsighttask_duration_seconds_count[30d]))",
     "legendFormat": "Hindsight last 30 days average runtime"
    },
    {
     "expr": "avg(rate(hindsighttask_duration_seconds_sum[3d])/rate(hindsighttask_duration_seconds_count[3d]))",
     "legendFormat": "Hindsight last 3 days average runtime"
    }
   ]
  },
  {
   "title": "String Unicode Average Runtime",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "\n\navg(rate(stringsunicodetask_duration_seconds_sum[30d])/rate(stringsunicodetask_duration_seconds_count[30d]))",
     "legendFormat": "String last 30 days average runtime"
    },
    {
     "expr": "\navg(rate(stringsunicodetask_duration_seconds_sum[3d])/rate(stringsunicodetask_duration_seconds_count[3d]))",
     "legendFormat": "String last 3 days average runtime"
    },
    {
     "expr": "job:stringsunicodetask_duration:rate3d:z_score",
     "legendFormat": "z_score"
    }
   ]
  },
  {
   "title": "SSHD Average Runtime",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "\n\navg(rate(sshdanalysistask_duration_seconds_sum[30d])/rate(sshdanalysistask_duration_seconds_count[30d]))",
     "legendFormat": "SSHD last 30 days average runtime"
    },
    {
     "expr": "\navg(rate(sshdanalysistask_duration_seconds_sum[3d])/rate(sshdanalysistask_duration_seconds_count[3d]))",
     "legendFormat": "SSHD last 3 days average runtime"
    }
   ]
  },
  {
   "title": "Jenkins Average Runtime",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "\navg(rate(jenkinsanalysistask_duration_seconds_sum[30d])/rate(jenkinsanalysistask_duration_seconds_count[30d]))",
     "legendFormat": "Jenkins last 30 days average runtime"
    },
    {
     "expr": "\navg(rate(jenkinsanalysistask_duration_seconds_sum[3d])/rate(jenkinsanalysistask_duration_seconds_count[3d]))",
     "legendFormat": "Jenkins last 3 days average runtime"
    }
   ]
  },
  {
   "title": "File Artifact Extraction Average Runtime",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "\n\navg(rate(fileartifactextractiontask_duration_seconds_sum[30d])/rate(fileartifactextractiontask_duration_seconds_count[30d]))",
     "legendFormat": "File artifact last 30 days average runtime"
    },
    {
     "expr": "\navg(rate(fileartifactextractiontask_duration_seconds_sum[3d])/rate(fileartifactextractiontask_duration_seconds_count[3d]))",
     "legendFormat": "File artifact last 3 days average runtime"
    }
   ]
  },
  {
   "title": "Photorec Average Runtime",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "\n\navg(rate(photorectask_duration_seconds_sum[30d])/rate(photorectask_duration_seconds_count[30d]))",
     "legendFormat": "Photorec last 30 days average runtime"
    },
    {
     "expr": "\n\navg(rate(photorectask_duration_seconds_sum[3d])/rate(photorectask_duration_seconds_count[3d]))",
     "legendFormat": "Photorec last 3 days average runtime"
    },
    {
     "expr": "job:photorectask_duration:rate3d:z_score",
     "legendFormat": "z_score"
    }
   ]
  },
  {
   "title": "Wordpress Task Average Runtime",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "\navg(rate(wordpressaccessloganalysistask_duration_seconds_sum[30d])/rate(wordpressaccessloganalysistask_duration_seconds_count[30d]))",
     "legendFormat": "Wordpress last 30 days average runtime"
    },
    {
     "expr": "\navg(rate(wordpressaccessloganalysistask_duration_seconds_sum[3d])/rate(wordpressaccessloganalysistask_duration_seconds_count[3d]))",
     "legendFormat": "Wordpress last 3 days average runtime"
    }
   ]
  },
  {
   "title": "Binary Extraction Average Runtime",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "\n\navg(rate(binaryextractortask_duration_seconds_sum[30d])/rate(binaryextractortask_duration_seconds_count[30d]))\n",
     "legendFormat": "Binary extraction last 30 days average runtime"
    },
    {
     "expr": "\n\navg(rate(binaryextractortask_duration_seconds_sum[3d])/rate(binaryextractortask_duration_seconds_count[3d]))",
     "legendFormat": "Binary extraction last 3 days average runtime"
    }
   ]
  },
  {
   "title": "Hadoop Task Average Runtime",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "\n\navg(rate(hadoopanalysistask_duration_seconds_sum[30d])/rate(hadoopanalysistask_duration_seconds_count[30d]))",
     "legendFormat": "Hadoop last 30 days average runtime"
    },
    {
     "expr": "\navg(rate(hadoopanalysistask_duration_seconds_sum[3d])/rate(hadoopanalysistask_duration_seconds_count[3d]))",
     "legendFormat": "Hadoop last 3 days average runtime"
    }
   ]
  },
  {
   "title": "Docker Enumeration Average Runtime",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "\n\navg(rate(dockercontainersenumerationtask_duration_seconds_sum[30d])/rate(dockercontainersenumerationtask_duration_seconds_count[30d]))",
     "legendFormat": "Docker enumeration last 30 days average runtime"
    },
    {
     "expr": "\navg(rate(dockercontainersenumerationtask_duration_seconds_sum[3d])/rate(dockercontainersenumerationtask_duration_seconds_count[3d]))",
     "legendFormat": "Docker enumeration last 3 days average runtime"
    }
   ]
  },
  {
   "title": "Fs Stat Average Riuntime",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "\navg(rate(fsstattask_duration_seconds_sum[30d])/rate(fsstattask_duration_seconds_count[30d]))",
     "legendFormat": "Fstat last 30 days average runtime"
    },
    {
     "expr": "avg(rate(fsstattask_duration_seconds_sum[3d])/rate(fsstattask_duration_seconds_count[3d]))",
     "legendFormat": "Fstat last 3 days average runtime"
    }
   ]
  }
 ]
}