apiVersion: apps/v1
kind: Deployment
metadata:
  name: turbinia-controller
  labels:
    app: turbinia-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: turbinia-controller
  template:
    metadata:
      annotations:
        prometheus.io/port: "9200"
        prometheus.io/scrape: "true"
      labels:
        app: turbinia-controller
    spec:
      serviceAccountName: turbinia
      # The grace period needs to be set to the largest task timeout as
      # set in the turbinia configuration file.
      initContainers:
        - name: init-filestore
          image: busybox:1.28
          command: ['sh', '-c', 'chmod go+w /mnt/turbiniavolume']
          volumeMounts:
            - mountPath: "/mnt/turbiniavolume"
              name: turbiniavolume
      containers:
        - name: controller
          image: us-docker.pkg.dev/osdfir-registry/turbinia/release/turbinia-controller:latest
          securityContext:
            privileged: true
          env:
            - name: TURBINIA_CONF
              valueFrom:
                configMapKeyRef:
                  name: turbinia-config
                  key: TURBINIA_CONF
            - name: TURBINIA_EXTRA_ARGS
              value: "-d"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - mountPath: "/var/run/lock"
              name: lockfolder
              readOnly: false
            - mountPath: /mnt/turbiniavolume
              name: turbiniavolume
          ports:
            - containerPort: 9200
          resources: 
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "8192Mi"
              cpu: "32000m"
      volumes:
        - name: lockfolder
          hostPath:
            path: /var/run/lock
        - name: turbiniavolume
          persistentVolumeClaim:
            claimName: turbiniavolume-claim
            readOnly: false
