apiVersion: v2
name: turbinia
version: 0.1.0
description: A Helm chart for Turbinia Kubernetes deployments.
keywords:
- turbinia
- dfir
- processing
- scaling
home: "https://github.com/google/turbinia"
dependencies:
- condition: redis.enabled
  name: redis
  version: 17.9.3
  repository: https://charts.bitnami.com/bitnami
maintainers:
  - name: wajihyassine
  - name: hacktobeer
  - name: aaronpeterson
sources:
- https://github.com/google/turbinia
icon: https://raw.githubusercontent.com/google/turbinia/master/web/src/assets/turbinia-logo-mark.png
appVersion: "20230315"
annotations:
  category: Security
  licenses: Apache-2.0