# coding: utf-8

"""
    Turbinia API Server

    Turbinia is an open-source framework for deploying,managing, and running distributed forensic workloads  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from turbinia_api_lib.paths.api_request_.post import CreateRequest
from turbinia_api_lib.paths.api_request_request_id.get import GetRequestStatus
from turbinia_api_lib.paths.api_request_summary.get import GetRequestsSummary


class TurbiniaRequestsApi(
    CreateRequest,
    GetRequestStatus,
    GetRequestsSummary,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
