# coding: utf-8

"""
    Turbinia API Server

    Turbinia is an open-source framework for deploying,managing, and running distributed forensic workloads  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from turbinia_api_lib.paths.api_config_request_options.get import GetRequestOptions
from turbinia_api_lib.paths.api_config_.get import ReadConfig


class TurbiniaConfigurationApi(
    GetRequestOptions,
    ReadConfig,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
