apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: turbinia-worker-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: turbinia-worker
  minReplicas: 3
  maxReplicas: 50
  targetCPUUtilizationPercentage: 90
