apiVersion: v1
kind: Service
metadata:
  name: {{ include "turbinia.fullname" . }}
  labels:
    {{- include "turbinia.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app.kubernetes.io/component: api
    {{- include "turbinia.selectorLabels" . | nindent 4 }}
