jobs_whitelist: 
  - ArtifactExtractionJob

PlasoJob:
  artifact_filters: 
    - WindowsAMCacheHveFile
    - WindowsAppCompatCache
    - WindowsUserRegistryFiles
    - WindowsPrefetchFiles
    - WindowsActivitiesCache
    - WindowsMostRecentApplication
    - WindowsUserJumpLists
    - WindowsOpenSavePidlMRU
  volumes: all
  partitions: all

FileArtifactExtractionTask:
  variants:
    amcache_install_win10_180x:
      custom_artifact_definitions: amcache_install_file.yaml
      artifact_filters: WindowsAMCacheInstallFile
    amcache_hive_win10_180x:
      artifact_filters: WindowsAMCacheHveFile
